version: '3.8'
services:
  moviebank:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: moviebank:django
    container_name: django_moviebank_container
    command: python manage.py runserver 0.0.0.0:8000