# Generated by Django 4.0.2 on 2022-09-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published_year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('watched', models.BooleanField(default=False)),
                ('genera', models.ManyToManyField(related_name='genre', to='movies.Genre')),
            ],
        ),
    ]
