# Generated by Django 4.0.2 on 2022-09-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='published_year',
            field=models.PositiveIntegerField(),
        ),
    ]
