# Generated by Django 4.0.2 on 2022-09-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_published_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genera',
            new_name='genre',
        ),
    ]
